[project]
name = "ctkknapsack"
version = "0.1.0"
description = "Showcases two algorithms solving the knapsack problem."
readme = "README.md"
authors = [
    { name = "loulct", email = "lecart-louis@orange.fr" }
]
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=6.0.0",
]

[project.scripts]
ctkknapsack = "ctkknapsack:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
]
